language: bash

sudo: false

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

script:
 - shellcheck homebrew/install.sh
 - shellcheck node/install.sh
 - shellcheck ruby/install.sh
 - shellcheck -x scripts/setup.sh
 - shellcheck -x sublime/install.sh
 - shellcheck -x zsh/install.sh
 - shellcheck -x install.sh

matrix:
  fast_finish: true

branches:
  only:
    - master
